pub const MidiMessage = union(enum) {
    noteOff: struct { channel: u4, key: u8, velocity: u8 },
    noteOn: struct { channel: u4, key: u8, velocity: u8 },
};

pub const MidiMessageHeader = packed struct {
    channel: u4,
    messageType: u4,
};

pub const Note = enum { A, B, C, D, E, F, G };

pub const NoteModifier = enum { Flat, Sharp };

pub const Tone = struct { note: Note, modifier: ?NoteModifier, octave: i8 };

pub fn midiKeyToTone(key: u8) Tone {
    switch (key) {
        0x00 => return .{ .note = Note.C, .modifier = null, .octave = -1 },
        0x01 => return .{ .note = Note.C, .modifier = NoteModifier.Sharp, .octave = -1 },
        0x02 => return .{ .note = Note.D, .modifier = null, .octave = -1 },
        0x03 => return .{ .note = Note.D, .modifier = NoteModifier.Sharp, .octave = -1 },
        0x04 => return .{ .note = Note.E, .modifier = null, .octave = -1 },
        0x05 => return .{ .note = Note.F, .modifier = null, .octave = -1 },
        0x06 => return .{ .note = Note.F, .modifier = NoteModifier.Sharp, .octave = -1 },
        0x07 => return .{ .note = Note.G, .modifier = null, .octave = -1 },
        0x08 => return .{ .note = Note.G, .modifier = NoteModifier.Sharp, .octave = -1 },
        0x09 => return .{ .note = Note.A, .modifier = null, .octave = -1 },
        0x0A => return .{ .note = Note.A, .modifier = NoteModifier.Sharp, .octave = -1 },
        0x0B => return .{ .note = Note.B, .modifier = null, .octave = -1 },
        0x0C => return .{ .note = Note.C, .modifier = null, .octave = 0 },
        0x0D => return .{ .note = Note.C, .modifier = NoteModifier.Sharp, .octave = 0 },
        0x0E => return .{ .note = Note.D, .modifier = null, .octave = 0 },
        0x0F => return .{ .note = Note.D, .modifier = NoteModifier.Sharp, .octave = 0 },
        0x10 => return .{ .note = Note.E, .modifier = null, .octave = 0 },
        0x11 => return .{ .note = Note.F, .modifier = null, .octave = 0 },
        0x12 => return .{ .note = Note.F, .modifier = NoteModifier.Sharp, .octave = 0 },
        0x13 => return .{ .note = Note.G, .modifier = null, .octave = 0 },
        0x14 => return .{ .note = Note.G, .modifier = NoteModifier.Sharp, .octave = 0 },
        0x15 => return .{ .note = Note.A, .modifier = null, .octave = 0 },
        0x16 => return .{ .note = Note.A, .modifier = NoteModifier.Sharp, .octave = 0 },
        0x17 => return .{ .note = Note.B, .modifier = null, .octave = 0 },
        0x18 => return .{ .note = Note.C, .modifier = null, .octave = 1 },
        0x19 => return .{ .note = Note.C, .modifier = NoteModifier.Sharp, .octave = 1 },
        0x1A => return .{ .note = Note.D, .modifier = null, .octave = 1 },
        0x1B => return .{ .note = Note.D, .modifier = NoteModifier.Sharp, .octave = 1 },
        0x1C => return .{ .note = Note.E, .modifier = null, .octave = 1 },
        0x1D => return .{ .note = Note.F, .modifier = null, .octave = 1 },
        0x1E => return .{ .note = Note.F, .modifier = NoteModifier.Sharp, .octave = 1 },
        0x1F => return .{ .note = Note.G, .modifier = null, .octave = 1 },
        0x20 => return .{ .note = Note.G, .modifier = NoteModifier.Sharp, .octave = 1 },
        0x21 => return .{ .note = Note.A, .modifier = null, .octave = 1 },
        0x22 => return .{ .note = Note.A, .modifier = NoteModifier.Sharp, .octave = 1 },
        0x23 => return .{ .note = Note.B, .modifier = null, .octave = 1 },
        0x24 => return .{ .note = Note.C, .modifier = null, .octave = 2 },
        0x25 => return .{ .note = Note.C, .modifier = NoteModifier.Sharp, .octave = 2 },
        0x26 => return .{ .note = Note.D, .modifier = null, .octave = 2 },
        0x27 => return .{ .note = Note.D, .modifier = NoteModifier.Sharp, .octave = 2 },
        0x28 => return .{ .note = Note.E, .modifier = null, .octave = 2 },
        0x29 => return .{ .note = Note.F, .modifier = null, .octave = 2 },
        0x2A => return .{ .note = Note.F, .modifier = NoteModifier.Sharp, .octave = 2 },
        0x2B => return .{ .note = Note.G, .modifier = null, .octave = 2 },
        0x2C => return .{ .note = Note.G, .modifier = NoteModifier.Sharp, .octave = 2 },
        0x2D => return .{ .note = Note.A, .modifier = null, .octave = 2 },
        0x2E => return .{ .note = Note.A, .modifier = NoteModifier.Sharp, .octave = 2 },
        0x2F => return .{ .note = Note.B, .modifier = null, .octave = 2 },
        0x30 => return .{ .note = Note.C, .modifier = null, .octave = 3 },
        0x31 => return .{ .note = Note.C, .modifier = NoteModifier.Sharp, .octave = 3 },
        0x32 => return .{ .note = Note.D, .modifier = null, .octave = 3 },
        0x33 => return .{ .note = Note.D, .modifier = NoteModifier.Sharp, .octave = 3 },
        0x34 => return .{ .note = Note.E, .modifier = null, .octave = 3 },
        0x35 => return .{ .note = Note.F, .modifier = null, .octave = 3 },
        0x36 => return .{ .note = Note.F, .modifier = NoteModifier.Sharp, .octave = 3 },
        0x37 => return .{ .note = Note.G, .modifier = null, .octave = 3 },
        0x38 => return .{ .note = Note.G, .modifier = NoteModifier.Sharp, .octave = 3 },
        0x39 => return .{ .note = Note.A, .modifier = null, .octave = 3 },
        0x3A => return .{ .note = Note.A, .modifier = NoteModifier.Sharp, .octave = 3 },
        0x3B => return .{ .note = Note.B, .modifier = null, .octave = 3 },
        0x3C => return .{ .note = Note.C, .modifier = null, .octave = 4 },
        0x3D => return .{ .note = Note.C, .modifier = NoteModifier.Sharp, .octave = 4 },
        0x3E => return .{ .note = Note.D, .modifier = null, .octave = 4 },
        0x3F => return .{ .note = Note.D, .modifier = NoteModifier.Sharp, .octave = 4 },
        0x40 => return .{ .note = Note.E, .modifier = null, .octave = 4 },
        0x41 => return .{ .note = Note.F, .modifier = null, .octave = 4 },
        0x42 => return .{ .note = Note.F, .modifier = NoteModifier.Sharp, .octave = 4 },
        0x43 => return .{ .note = Note.G, .modifier = null, .octave = 4 },
        0x44 => return .{ .note = Note.G, .modifier = NoteModifier.Sharp, .octave = 4 },
        0x45 => return .{ .note = Note.A, .modifier = null, .octave = 4 },
        0x46 => return .{ .note = Note.A, .modifier = NoteModifier.Sharp, .octave = 4 },
        0x47 => return .{ .note = Note.B, .modifier = null, .octave = 4 },
        0x48 => return .{ .note = Note.C, .modifier = null, .octave = 5 },
        0x49 => return .{ .note = Note.C, .modifier = NoteModifier.Sharp, .octave = 5 },
        0x4A => return .{ .note = Note.D, .modifier = null, .octave = 5 },
        0x4B => return .{ .note = Note.D, .modifier = NoteModifier.Sharp, .octave = 5 },
        0x4C => return .{ .note = Note.E, .modifier = null, .octave = 5 },
        0x4D => return .{ .note = Note.F, .modifier = null, .octave = 5 },
        0x4E => return .{ .note = Note.F, .modifier = NoteModifier.Sharp, .octave = 5 },
        0x4F => return .{ .note = Note.G, .modifier = null, .octave = 5 },
        0x50 => return .{ .note = Note.G, .modifier = NoteModifier.Sharp, .octave = 5 },
        0x51 => return .{ .note = Note.A, .modifier = null, .octave = 5 },
        0x52 => return .{ .note = Note.A, .modifier = NoteModifier.Sharp, .octave = 5 },
        0x53 => return .{ .note = Note.B, .modifier = null, .octave = 5 },
        0x54 => return .{ .note = Note.C, .modifier = null, .octave = 6 },
        0x55 => return .{ .note = Note.C, .modifier = NoteModifier.Sharp, .octave = 6 },
        0x56 => return .{ .note = Note.D, .modifier = null, .octave = 6 },
        0x57 => return .{ .note = Note.D, .modifier = NoteModifier.Sharp, .octave = 6 },
        0x58 => return .{ .note = Note.E, .modifier = null, .octave = 6 },
        0x59 => return .{ .note = Note.F, .modifier = null, .octave = 6 },
        0x5A => return .{ .note = Note.F, .modifier = NoteModifier.Sharp, .octave = 6 },
        0x5B => return .{ .note = Note.G, .modifier = null, .octave = 6 },
        0x5C => return .{ .note = Note.G, .modifier = NoteModifier.Sharp, .octave = 6 },
        0x5D => return .{ .note = Note.A, .modifier = null, .octave = 6 },
        0x5E => return .{ .note = Note.A, .modifier = NoteModifier.Sharp, .octave = 6 },
        0x5F => return .{ .note = Note.B, .modifier = null, .octave = 6 },
        0x60 => return .{ .note = Note.C, .modifier = null, .octave = 7 },
        0x61 => return .{ .note = Note.C, .modifier = NoteModifier.Sharp, .octave = 7 },
        0x62 => return .{ .note = Note.D, .modifier = null, .octave = 7 },
        0x63 => return .{ .note = Note.D, .modifier = NoteModifier.Sharp, .octave = 7 },
        0x64 => return .{ .note = Note.E, .modifier = null, .octave = 7 },
        0x65 => return .{ .note = Note.F, .modifier = null, .octave = 7 },
        0x66 => return .{ .note = Note.F, .modifier = NoteModifier.Sharp, .octave = 7 },
        0x67 => return .{ .note = Note.G, .modifier = null, .octave = 7 },
        0x68 => return .{ .note = Note.G, .modifier = NoteModifier.Sharp, .octave = 7 },
        0x69 => return .{ .note = Note.A, .modifier = null, .octave = 7 },
        0x6A => return .{ .note = Note.A, .modifier = NoteModifier.Sharp, .octave = 7 },
        0x6B => return .{ .note = Note.B, .modifier = null, .octave = 7 },
        0x6C => return .{ .note = Note.C, .modifier = null, .octave = 8 },
        0x6D => return .{ .note = Note.C, .modifier = NoteModifier.Sharp, .octave = 8 },
        0x6E => return .{ .note = Note.D, .modifier = null, .octave = 8 },
        0x6F => return .{ .note = Note.D, .modifier = NoteModifier.Sharp, .octave = 8 },
        0x70 => return .{ .note = Note.E, .modifier = null, .octave = 8 },
        0x71 => return .{ .note = Note.F, .modifier = null, .octave = 8 },
        0x72 => return .{ .note = Note.F, .modifier = NoteModifier.Sharp, .octave = 8 },
        0x73 => return .{ .note = Note.G, .modifier = null, .octave = 8 },
        0x74 => return .{ .note = Note.G, .modifier = NoteModifier.Sharp, .octave = 8 },
        0x75 => return .{ .note = Note.A, .modifier = null, .octave = 8 },
        0x76 => return .{ .note = Note.A, .modifier = NoteModifier.Sharp, .octave = 8 },
        0x77 => return .{ .note = Note.B, .modifier = null, .octave = 8 },
        0x78 => return .{ .note = Note.C, .modifier = null, .octave = 9 },
        0x79 => return .{ .note = Note.C, .modifier = NoteModifier.Sharp, .octave = 9 },
        0x7A => return .{ .note = Note.D, .modifier = null, .octave = 9 },
        0x7B => return .{ .note = Note.D, .modifier = NoteModifier.Sharp, .octave = 9 },
        0x7C => return .{ .note = Note.E, .modifier = null, .octave = 9 },
        0x7D => return .{ .note = Note.F, .modifier = null, .octave = 9 },
        0x7E => return .{ .note = Note.F, .modifier = NoteModifier.Sharp, .octave = 9 },
        0x7F => return .{ .note = Note.G, .modifier = null, .octave = 9 },
        else => unreachable,
    }
}

pub fn decodeMessage(msg: []const u8) ?MidiMessage {
    const messageHeader = @bitCast(MidiMessageHeader, msg[0]);
    return if (messageHeader.messageType == 0b1001) .{
        .noteOn = .{
            .channel = messageHeader.channel,
            .key = msg[1],
            .velocity = msg[2],
        },
    } else if (messageHeader.messageType == 0b1000) .{
        .noteOff = .{
            .channel = messageHeader.channel,
            .key = msg[1],
            .velocity = msg[2],
        },
    } else null;
}
